### ISSUE TITLE
Support for iframe click events

### ISSUE THREAD

**Issue by jokerslab** [checkly/puppeteer-recorder#12]
I would love to see support for recording events from iframes and populating the script with the appropriate frame selection.
`const frames = await page.frames();
const curFrame = frames.find(f => f.name() === 'activeFrame');
await curFrame.click('#selector')`

**Comment by tnolet** [comment]
Hi @jokerslab Could you give a little bit more context about the what you exactly mean with "populating the script with the appropriate frame selection". I'm open to new feature suggestions, I just need a bit more about what does it do and what the expect behaviour should be.

**Comment by jokerslab** [comment]
If I have an html page with multiple iframes, and I start the recorder, no click events are captured from any of the elements in the iframe. I would expect the recorder to record events from all frames within the page. Additionally, when running puppeteer the click event has to be called on the frame where the selector/element parent document is. 

Thus I would imagine whenever capturing a click from an iframe, you would want to capture the name or id of the iframe so that when generating or running the script from the recorder you can call 
frame.click(selector)
with the correct frame from page.frames()

**Comment by rationalthinker1** [comment]
For example:
https://www.goodmanmfg.com/product-registration
I want to record on this page. The interactions does not record because it is in within a iframe.

**Comment by rationalthinker1** [comment]
I don't think that it was ever implemented.

**Comment by chris2kus31** [comment]
Was this ever resolved?  I am using the puppeteer recorder but there is a iframe payment form that when I selected, the recorder does not capture.  Is this an issue on my side or on the recorder itself?  The URL is https://giving.kcm.org/

**Comment by tnolet** [comment]
@chris2kus31 resolved is a bit tricky to define. I have working examples, but things might break in unexpected ways depending on timing and the actual DOM makeup. I will have a look at your example when I get the time.

**Comment by rationalthinker1** [comment]
@tnolet If you look at my example from last year, you would see that it still doesn't work.

**Comment by tnolet** [comment]
Please contribute either a triage/analysis if what is going wrong or a fix for the bug if this is a high priority item for you.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by rationalthinker1** [comment]
@tnolet you are right. I'll look at it. My intention wasn't to demand this.
