### ISSUE TITLE
Error thrown when Recording started

### ISSUE THREAD

**Issue by jakefromqa** [checkly/puppeteer-recorder#13]
Chrome Version 68.0.3440.106, Puppeteer Recorder 0.2.0
Steps: 
1. run: npm run dev
2. load unpacked extension in Chrome
3. Launch the Plugin and click "Record"
4. Notice the following error - https://screencast.com/t/C5fXkTMJrjz
5. after interacting with a page, I notice there is no script saved off.

**Comment by tnolet** [comment]
@jakefromqa Yeah, sorry that was a botched release. Still getting the hang of how storage works in extension. Checkout release 0.2.1 that was released right after. It should already be live on the Web Store. 0.2.0 is DOA.
