### ISSUE TITLE
Google search + tab does not record input

### ISSUE THREAD

**Issue by tnolet** [checkly/puppeteer-recorder#21]
...here's another video, this time with google search. I hit "tab" when going from search box to "submit" button: https://www.youtube.com/watch?v=gSf7s0NwFdg&feature=youtu.be

**Comment by tnolet** [comment]
@aslushnikov I tried to reproduce, but typing something in the google search box and hitting tab records the thing correctly, AFAICS. See the GIF below. 


![sep-06-2018 19-54-14](https://user-images.githubusercontent.com/3802923/45175859-b160d680-b20e-11e8-8529-5603b1560369.gif)

**Comment by aslushnikov** [comment]
@tnolet ah you did it differently. I typed, hit "tab" to select "google search", and then hit "enter" to search. After that I stopped the recording

**Comment by tnolet** [comment]
@aslushnikov yeah, that's why TAB is kind of a shitty way to mark the recording "cut" because TAB is used to navigate around the screen. The current way of recording keyboard input relies on the user to define when he/she is done with typing. Any ideas on what would be better? Preferably we would need a key combination not used in browser or desktop navigation. Or maybe an "on screen" button?

**Comment by aslushnikov** [comment]
ok it looks like it has something to do with our corp account or default extensions. If I try on a chromium instance this scenario works just fine.

Feel free to close this!
