### ISSUE TITLE
Record basic forms

### ISSUE THREAD

**Issue by tnolet** [checkly/puppeteer-recorder#3]
Usefulness of the plugin is very much depended on automating the time intensive parts of testing and crawling. Number one is probably filling out forms. This extension should be able to record all the things that are in a typical Bootstrap-type form:

- [x] select / drop downs
- [x] radio buttons
- [x] check boxes
- [x] text areas
- [x] button and link clicks

**Comment by manoflinux** [comment]
I see I am not the only person with problems recording what is typed into a input form. 
Everything else seems to be recorded. 
Just wanted to also say this an awesome project and can't wait till its more done.

**Comment by tnolet** [comment]
@manoflinux please remember to hit tab when typing in input fields. This functionality is now just a copy & paste from Daydream. Will iterate on it more.

**Comment by shobhitchittora** [comment]
I'm facing the same issue here. Not able to record data input event to input fields.
