### ISSUE TITLE
selector should always prefer ID tags over classes

### ISSUE THREAD

**Issue by tnolet** [checkly/puppeteer-recorder#32]
currently, this is possible. A bunch of generated classes with a perfectly fine ID tag at the end. In these cases, the ID tag should "win" and the class selectors disregarded.
```
  await page.waitForSelector('.loCvjm > .dqCcvp > .iczaPt > .hkOTKM > #ListingSort--SortPicker')
  await page.click('.loCvjm > .dqCcvp > .iczaPt > .hkOTKM > #ListingSort--SortPicker')
```

**Comment by rationalthinker1** [comment]
I am thinking something like this:
`const optimizedMinLength = (e.target.id) ? 2 : 10
      const selector = this.dataAttribute && e.target.hasAttribute && e.target.hasAttribute(this.dataAttribute)
        ? formatDataSelector(e.target, this.dataAttribute)
        : finder(e.target, {seedMinLength: 5, optimizedMinLength: optimizedMinLength})`
