### ISSUE TITLE
Can only record once after installation, not again

### ISSUE THREAD

**Issue by tnolet** [checkly/puppeteer-recorder#4]
Some report that they can only record one script after installation of the extension and not anymore. I can not reproduce (tried on a fresh Chrome installation + extension installation). Anyone suffering from this, please set logging in the console to "verbose" and report in this issue.

![image](https://user-images.githubusercontent.com/3802923/44194637-e2ca1300-a136-11e8-93fd-68b33652691e.png)

**Comment by aslushnikov** [comment]
My repro steps:

1. Navigate page to `https://pptr.dev`
2. Click the "record" button in extension
3. Click on the "search" field on the website
4. Type "eval"
5. Mouse-click on the "page.evaluate" suggestion (should be the first in list)
6. Hit "stop recording" in extension. Note: before stopping, I can see that extension successfully traced
the input events.

After the last step, extension provides me with a pptr snippet:

```js
const puppeteer = require('puppeteer');
(async () => {
  const browser = await puppeteer.launch()
  const page = await browser.newPage()
  await page.click('input')

  await browser.close()
})()
```

There are no errors in the console; here's what I get:

![image](https://user-images.githubusercontent.com/746130/44235234-a9f16480-a15d-11e8-8453-e2bf85deb0ad.png)

**Comment by tnolet** [comment]
@aslushnikov really weird. I have no issues recording multiple sessions on pptr.dev  I will try some more to reproduce this and add some extra debug statements.

**Comment by tnolet** [comment]
The best way to triage this would be to write a test. I have the installation of the extension working in a [test](https://github.com/checkly/puppeteer-recorder/blob/master/src/__e2e-tests__/e2e.spec.js), I'm just looking for pointers on how to activate it. Any tips from your side @aslushnikov on how to get that working? Some custom CDP calls I can do?

**Comment by aslushnikov** [comment]
@tnolet I wonder if it has something to do with the corporate nature of our machines. I'll try it on my personal one tomorrow.

**Comment by aslushnikov** [comment]
>  I'm just looking for pointers on how to activate it. Any tips from your side @aslushnikov on how to get that working? Some custom CDP calls I can do?

@tnolet you can connect to background page since recently: [Working with Chrome Extensions](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#working-with-chrome-extensions). Is this enough?

**Comment by tnolet** [comment]
@aslushnikov O jeez, totally missed that! That should work, or I think I can make it work. You guys are going to fast with Puppeteer 😮

**Comment by aslushnikov** [comment]
> See 5ff27cb I hope in the new update (probably ship tomorrow) you will no longer have the reported issues.

@tnolet I'd love to try it out!

P.S. My home computer didn't launch, so I failed to see if these are related to our corp policy.

**Comment by vino24** [comment]
same problem, hope for resloved in nexe version

**Comment by tnolet** [comment]
(@aslushnikov provided this video https://www.youtube.com/watch?v=9bzDU56iyJQ&feature=youtu.be outside of this thread )
I'm not seeing the "can only record after installation" bug in this video. I can see one session being recorded and then the video stops.
I can see two different issues though:

1. The input "evaluate" is not recorded. This is solved by hitting TAB after typing. Only in TAB is the actual sentence recorded. That's a bit confusing and I will think about a better solution for this.

2. The JSHandle link is not recorded. That is totally an issue. It is because the link is not instrumented with a listener. So nothing is recorded. See the image below.

![image](https://user-images.githubusercontent.com/3802923/45082377-7a4cd100-b0f9-11e8-9707-7d05777bd8bc.png)

This is pretty specific for how pptr.dev loads and how the `content-script.js` is inserted. I will look into it.
FYI: A correctly instrumented link has a `data-pptr-rec` attribute as seen below.
![image](https://user-images.githubusercontent.com/3802923/45082426-96e90900-b0f9-11e8-9074-417e070f9afc.png)

**Comment by aslushnikov** [comment]
> I'm not seeing the "can only record after installation" bug in this video. 

@tnolet Interestingly, i think this no longer happens with 0.3.0!

> The input "evaluate" is not recorded. This is solved by hitting TAB after typing. Only in TAB is the actual sentence recorded. That's a bit confusing and I will think about a better solution for this.

This unfortunately didn't work for me - here's another video, this time with google search. I hit "tab" when going from search box to "submit" button: https://www.youtube.com/watch?v=gSf7s0NwFdg&feature=youtu.be

**Comment by tnolet** [comment]
@aslushnikov Ok, I will close this issue and port over the other issues. Thanks for helping out!
