### ISSUE TITLE
Recording actions on a Chrome-Extension

### ISSUE THREAD

**Issue by harith1996** [checkly/puppeteer-recorder#43]
On hitting record, then loading a Chrome-Extension URL (for example, the settings page of a Chrome-Extension), doing actions on this page and going back to Puppeteer Recorded, there is no script generated. 

This might be related to issue #22

**Comment by tnolet** [comment]
Hi, this is I guess not supported. At least not tested. If you want support for testing Chrome extension URLs please provide a PR with a unit test.
