### ISSUE TITLE
Is it possible to record google analytics login?

### ISSUE THREAD

**Issue by Unitech** [checkly/puppeteer-recorder#44]
Hi, I’ve noticed that some input forms of google apps have dynamic id and classes. Is there any solution to record the insertion of credentials on these kind of dynamic forms? Thanks

**Comment by tnolet** [comment]
Hi @Unitech, this really really depends on how dynamic they are. If you have control over the code,  you can add data attributes that remain constant while ID tags and class might be dynamic.

In your case, the Google apps are of course not under you control. This makes things a little more difficult.

I would opt for using the browsers Developer Console to grab a selector and see how that works.
![image](https://user-images.githubusercontent.com/3802923/52875985-0443a000-3156-11e9-8eb7-4eef8eb00e7b.png)

**Comment by Unitech** [comment]
ok thanks for your advice, closing
