### ISSUE TITLE
Recording does not work

### ISSUE THREAD

**Issue by TroySK** [checkly/puppeteer-recorder#46]
I followed the instructions in the Readme and loaded the unpacked extension in Chrome. After I press record and enter an URL, the icon changes from `rec` to `wait` and stays there. Navigating to other pages does not return the icon to `rec` state. If I stop, nothing is recorded in the script. I used Wikipedia as test.

**Comment by tnolet** [comment]
Hi, @TroySK please just install the plugin from the Chrome store. https://chrome.google.com/webstore/detail/puppeteer-recorder/djeegiggegleadkkbgopoonhjimgehda

The development environment requires knowledge of Node.js and a particular environment.

**Comment by TroySK** [comment]
Hii @tnolet;

I want to make changes to the extension. I am comfortable with JavaScript and should be able to setup the environment if you could help me with some documentation.

**Comment by tnolet** [comment]
@TroySK the docs as they are work fine. I cannot debug your local environment and assess why some things don't work. I just reproduced on wikipedia and it works fine in my end.

Only thing I can add is to check de debug logs (enable in the Chrome developer tools) and check the output log of the extension (this is a separate tab, you can find it in the extension overview where you imported it.

Sorry I cannot be more helpful than this.

**Comment by TroySK** [comment]
Thanks @tnolet. Let me try those.
