### ISSUE TITLE
CSS selector library is not very good, should replace

### ISSUE THREAD

**Issue by tnolet** [checkly/puppeteer-recorder#5]
The library used for generating CSS selectors [0] from HTML nodes is a bit flaky. Even the https://checklyhq.com/docs/ generates css selectors that don't work in Puppeteer.

For a link on the side bar it generates
```
:nth-child(1) > .sidebar-menu-sub > :nth-child(4) > a
```

[0] https://github.com/fczbkk/css-selector-generator

**Comment by transitive-bullshit** [comment]
[finder](https://github.com/antonmedv/finder) seems like the best library I could find for this purpose.

Also see this (somewhat dated) comparison: https://github.com/fczbkk/css-selector-generator-benchmark

**Comment by tnolet** [comment]
@transitive-bullshit I'm going to do some testing on this.
