### ISSUE TITLE
Use nth-of-type/nth-child instead of class names for selectors

### ISSUE THREAD

**Issue by ljocampo** [checkly/puppeteer-recorder#62]
Script records following selector:
```
.ag-cell-focus > .ag-react-container > .sc-caSCKo > .MuiSvgIcon-root-48 > path:nth-child(2)
```
 
Next time the page is reloaded for the same element selector has changed to:
```
.ag-cell-focus > .ag-react-container > .sc-caSCKo > .MuiSvgIcon-root-919 > path:nth-child(2)
```

**Comment by tnolet** [comment]
@ljocampo this is normal expected behaviour from the (probably React) library you are using and has nothing to do with Puppeteer recorder. Best way to solve this is use @ephetic solution or add #ID tags to your elements.

**Comment by ljocampo** [comment]
Unfortunately the proposed solution is not viable for me since I do not have access to the source code of the site I'm puppeteering. Please consider having an option to use nth hierarchy.
