### ISSUE TITLE
Suggestion: pptr-testing-library mode

### ISSUE THREAD

**Issue by MynockSpit** [checkly/puppeteer-recorder#63]
This is probably very much out of scope, but here's a thought:

Add a [`pptr-testing-library`](https://github.com/testing-library/pptr-testing-library) mode that tries first to produce `pptr-testing-library` queries, and falls back on the current queries if they don't work. Honestly don't know how many other people would want it, but it'd make me much more confident in my selectors.

**Comment by tnolet** [comment]
Hi @MynockSpit I think this is such a custom thing, that we probably want a different solution to this. CSS selector are mighty tricky to determine dynamically. A custom library is just a tricky solution to a tricky problem. Thanks for contributing though.
