### ISSUE TITLE
Not able too generate script to fill text boxes.

### ISSUE THREAD

**Issue by shobhitchittora** [checkly/puppeteer-recorder#65]
Tested this in Chrome as well as in Chromium. I'm not able to see any input script being generated for the keydown events recorded.

![puppeteer-recorder-issue](https://user-images.githubusercontent.com/4711855/65064650-828f4b80-d99e-11e9-88ee-5a85f622dccc.gif)

**Comment by tnolet** [comment]
Hey @shobhitchittora you need to hit the TAB key to "commit" the key downs.

https://github.com/checkly/puppeteer-recorder#usage

There is no other way to register the begin / end of text input for now.
