### ISSUE TITLE
[Feature Request] Support for Playwright

### ISSUE THREAD

**Issue by mxschmitt** [checkly/puppeteer-recorder#82]
Hey,

the chrome extension seems to have a really good foundation and it would be good to provide maybe also support for the new [Playwright](https://github.com/microsoft/playwright/) project. It's basically mostly the same except with cross-browser support and a few API calls were simplified.

What do you think?

**Comment by tnolet** [comment]
Hi @mxschmitt this is a great idea. I just created this issue explaining our way forward https://github.com/checkly/puppeteer-recorder/issues/83

**Comment by tnolet** [comment]
@mxschmitt We are reserving time to look into this. It would possibly involve a renaming of the project and that might be a bit of a hassle. But expect some action here soon.

**Comment by tnolet** [comment]
Ok, I had a look. A feature-equivalent version of Puppeteer Recorder with Playwright support is quite simple. All events are already abstracted and can be fed to a different code generator. On the UI side we would just generate both scripts on finishing a recording and show each result in a separate tab. 

We can allow users to specific which tab should be there default tab to minimise annoying switching when you are just using either framework.

The bigger thing would be "rebranding" the extension. AFAICS we can do that without "punishment" from Google.

 Here are the items I see:

- [ ] Move `CodeGenerator.js` to `PuppeteerCodeGenerator.js`
- [ ] Add `PlaywrightCodeGenerator.js` 
- [ ] Call both generators on finishing the code and store in separate store entities.
- [ ] Add tabbed layout to result: one Puppeteer tab, one Playwright tab
- [ ] Update docs, images, store copy and GitHub repo to reflect "new" status

**Comment by maxigimenez** [comment]
Closing this issue given that the feature has been merged to master 🎉
